root: true

env:
  es6: true
  node: true
  mocha: true

extends: 'eslint:recommended'

parserOptions:
  sourceType: module

rules:
  ### Possible Errors
  for-direction: error
  getter-return: error
  no-await-in-loop: error
  no-prototype-builtins: error
  valid-jsdoc: error

  ### Best Practices
  array-callback-return: error
  class-methods-use-this: error
  consistent-return: error
  curly: error
  default-case: error
  dot-location:
    - error
    - property
  dot-notation: error
  eqeqeq: error
  guard-for-in: error
  no-alert: error
  no-caller: error
  no-case-declarations: error
  no-empty-function: error
  no-empty-pattern: error
  no-eq-null: error
  no-eval: error
  no-extend-native: error
  no-extra-bind: error
  #no-floating-decimal: error
  no-implicit-coercion: error
  no-implicit-globals: error
  no-implied-eval: error
  no-invalid-this: error
  no-labels: error
  no-lone-blocks: error
  no-loop-func: error
  #no-magic-numbers: error
  no-multi-spaces: error
  no-multi-str: error
  no-new: error
  no-new-func: error
  no-new-wrappers: error
  no-octal: error
  no-octal-escape: error
  no-param-reassign: error
  no-proto: error
  no-redeclare: error
  no-return-assign: error
  no-script-url: error
  no-self-assign: error
  no-self-compare: error
  no-sequences: error
  no-throw-literal: error
  no-unmodified-loop-condition: error
  no-unused-expressions: error
  no-useless-call: error
  no-useless-concat: error
  no-useless-return: error
  no-warning-comments: warn
  no-with: error
  radix: error
  require-await: error

  ### Strict Mode
  strict: error

  ### Variables
  no-catch-shadow: error
  no-shadow: warn
  no-shadow-restricted-names: error
  no-undef: error
  no-undef-init: error
  no-undefined: error
  no-unused-vars:
    - error
    -
      argsIgnorePattern: '^_'
  no-use-before-define: error

  ### Node.js and CommonJS
  no-sync: error

  ### Stylistic Issues
  array-bracket-newline: error
  array-bracket-spacing: error
  #array-element-newline: error
  block-spacing: error
  brace-style:
    - error
    - 1tbs
    -
      allowSingleLine: false
  camelcase: error
  comma-dangle:
    - error
    - always-multiline
  comma-spacing: error
  comma-style: error
  computed-property-spacing: error
  consistent-this: error
  eol-last: error
  func-call-spacing: error
  #func-names: error
  func-style: error
  indent:
    - error
    - 2
    -
      SwitchCase: 1
  key-spacing: error
  keyword-spacing: error
  linebreak-style:
    - error
    - unix
  lines-around-comment:
    - error
    -
      allowBlockStart: true
      allowObjectStart: true
      allowArrayStart: true
  max-len:
    - error
    - 100
  new-parens: error
  #newline-per-chained-call: error
  no-array-constructor: error
  no-lonely-if: error
  no-mixed-operators: error
  no-multiple-empty-lines: error
  no-new-object: error
  no-tabs: error
  no-trailing-spaces: error
  no-underscore-dangle:
    - error
    -
      allowAfterThis: true
  no-unneeded-ternary: error
  no-whitespace-before-property: error
  object-curly-newline: error
  object-curly-spacing:
    - error
    - always
  #one-var: error
  #one-var-declaration-per-line: error
  operator-assignment: error
  operator-linebreak: error
  padded-blocks:
    - error
    - never
  quote-props:
    - error
    - as-needed
  quotes:
    - error
    - single
  semi:
    - error
    - always
  semi-spacing: error
  space-before-blocks: error
  space-before-function-paren:
    - error
    - never
  space-in-parens: error
  space-infix-ops:
    - error
    -
      int32Hint: true
  space-unary-ops: error
  spaced-comment: error
  switch-colon-spacing: error
  template-tag-spacing: error
  wrap-regex: error

  ### ECMAScript 6
  arrow-body-style: error
  arrow-parens: error
  arrow-spacing: error
  generator-star-spacing: error
  no-confusing-arrow:
    - error
    -
      allowParens: true
  no-const-assign: error
  no-duplicate-imports: error
  no-useless-computed-key: error
  no-useless-rename: error
  no-var: error
  object-shorthand: error
  prefer-arrow-callback: error
  prefer-const: error
  prefer-rest-params: error
  prefer-spread: error
  prefer-template: error
  rest-spread-spacing: error
  symbol-description: error
  template-curly-spacing:
    - error
    - always
  yield-star-spacing: error
